version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js..."
      - curl -sL https://rpm.nodesource.com/setup_16.x | bash -
      - yum install -y nodejs
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running tests..."
      - npm test
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - app.js
    - package.json
    - package-lock.json
    - node_modules/**/*
    - scripts/**/*
    - appspec.yml
  discard-paths: no 